const sitesObj = {
    "androidpolice.com": "https://www.androidpolice.com/subscribe-donate/",
    "archive.org": "https://archive.org/donate/",
    "archlinux.org": "https://www.archlinux.org/donate/",
    "audacityteam.org": "https://www.audacityteam.org/donate/",
    "blender.org": "https://fund.blender.org/",
    "debian.org": "https://www.debian.org/donations",
    "f-droid.org": "https://f-droid.org/en/donate/",
    "firefox.com": "https://donate.mozilla.org/",
    "freebsd.org": "https://www.freebsdfoundation.org/donate/",
    "gimp.org": "https://www.gimp.org/donating/",
    "gutenberg.org": "http://www.gutenberg.org/wiki/Gutenberg:Project_Gutenberg_Needs_Your_Donation",
    "inkscape.org": "https://inkscape.org/support-us/donate/",
    "joinmastodon.org": "https://www.patreon.com/mastodon",
    "krita.org": "https://krita.org/en/support-us/donations/",
    "libreoffice.org": "https://www.libreoffice.org/donate/",
    "libretro.com": "https://www.patreon.com/libretro",
    "lineageos.org": "https://www.lineageos.org/about/",
    "linuxmint.com": "https://www.linuxmint.com/donors.php",
    "mediawiki.org": "https://donate.wikimedia.org/",
    "mozilla.org": "https://donate.mozilla.org/",
    "notepad-plus-plus.org": "https://notepad-plus-plus.org/donate/",
    "obsproject.com": "https://obsproject.com/contribute",
    "retroarch.com": "http://www.retroarch.com/index.php?page=donate",
    "shotcut.org": "https://shotcut.org/download/",
    "simplemobiletools.com": "https://www.simplemobiletools.com/donate/",
    "theguardian.com": "https://support.theguardian.com/contribute",
    "videolan.org": "https://www.videolan.org/contribute.html#money",
    "wikibooks.org": "https://donate.wikimedia.org/",
    "wikidata.org": "https://donate.wikimedia.org/",
    "wikimedia.org": "https://donate.wikimedia.org/",
    "wikimediafoundation.org": "https://donate.wikimedia.org/",
    "wikinews.org": "https://donate.wikimedia.org/",
    "wikipedia.org": "https://donate.wikimedia.org/",
    "wikiquote.org": "https://donate.wikimedia.org/",
    "wikisource.org": "https://donate.wikimedia.org/",
    "wikiversity.org": "https://donate.wikimedia.org/",
    "wikivoyage.org": "https://donate.wikimedia.org/",
    "wiktionary.org": "https://donate.wikimedia.org/"
}

// Sort in VS Code: https://marketplace.visualstudio.com/items?itemName=richie5um2.vscode-sort-json
// CTRL+SHIFT+P -> Sort JSON